foq_elastica:
    clients:
        default:
            host: localhost
            port: 9200
    indexes:
        doc:
            settings:
                index:
                    analysis:
                        analyzer:
                            search_analyzer:
                                type: custom
                                tokenizer: standard
                                filter: [lowercase, my_ngram]

                        filter:
                            my_ngram:
                                type: nGram
                                min_gram: 2
                                max_gram: 10

            client: default
            types:
                font:
                    mappings:
                        fontFamily: { boost: 10, analyzer: search_analyzer }
                        sources:  { boost: 8 }
                    doctrine:
                        driver: mongodb
                        model: FontCrawler\CrawlerBundle\Document\Font
                        provider:
                        finder:
