foq_elastica:
    clients:
        default:
            host: localhost
            port: 9200
    indexes:
        doc:
            settings:
                index:
                    analysis:
                        analyzer: 
                            my_analyzer: 
                                type: custom
                                tokenizer: lowercase
                                filter   : [my_ngram]
                            filter: 
                                my_ngram: 
                                    type: "nGram"
                                    min_gram: 3
                                    max_gram: 5
            types:
                font:
                    mappings:
                        fontFamily: { boost: 10, analyzer: my_analyzer }
                        sources:    { boost: 8 }
                    doctrine:
                        driver: mongodb
                        model:  FontCrawler\CrawlerBundle\Document\Font
                        provider:
                        finder:
