
# This file is part of the fontcrawler package.
#
# (c) Dennis Dietrich <d.dietrich84@googlemail.com/>
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

media:
    resource: "@FontCrawlerCrawlerBundle/Controller/FontController.php"
    type:     annotation
